[package]
name = "porcula"
version = "0.1.14"
authors = ["alexey.s.v.br@gmail.com"]
edition = "2018"
publish = false

[profile.release]
opt-level = "s"
codegen-units = 1
lto = "fat"

[dependencies]
zip = { version = "0.5", default-features = false, features = ["deflate"] }
base64 = "0.12"
regex = "1.3"
rouille = { version = "3.0", default-features = false }
rand = "0.7"
chardet = "0.2"
htmlescape = "0.3"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
ctrlc = "3.1"
deepsize = "0.1"
crossbeam = "0.7"
crossbeam-utils = "0.7"
tantivy = { version = "0.12", features = ["mmap"] }
quick-xml = { version = "0.18", features = ["encoding"] }
image = { version = "0.23", default-features = false, features = ["jpeg","png","gif","bmp"] }
encoding = { version = "0.2", default-features = false }
clap = { version = "2.33", default-features = false }
atom_syndication = "0.9"
chrono = "0.4"
percent-encoding = "2.1"
