[package]
name = "porcula"
version = "0.1.7"
authors = ["alexey.s.v.br@gmail.com"]
edition = "2018"
publish = false

[profile.release]
opt-level = "s"
codegen-units = 1
lto = "fat"

[dependencies]
zip = { version = "0.5.5", default-features = false, features = ["deflate"] }
base64 = "0.12.0"
regex = "1.3.5"
rouille = "3.0.0"
rand = "0.7.3"
chardet = "0.2.4"
htmlescape = "0.3.1"
serde = "1.0.104"
serde_json = "1.0.48"
lazy_static = "1.4.0"
ctrlc = "3.1.4"
deepsize = "0.1.2"
crossbeam = "0.7"
crossbeam-utils = "0.7"
tantivy = { version = "0.12.0", features = ["mmap"] }
quick-xml = { version = "0.18.1", features = ["encoding"] }
image = { version = "0.23.1", default-features = false, features = ["jpeg","png","gif","bmp"] }
encoding = { version = "0.2.33", default-features = false }
clap = { version = "2.33.0", default-features = false }
