[package]
name = "porcula"
version = "0.4.0"
authors = ["alexey.s.v.br@gmail.com"]
edition = "2018"
publish = false

[profile.dev.package.adler]
opt-level = 3
[profile.dev.package.adler32]
opt-level = 3
[profile.dev.package.miniz_oxide]
opt-level = 3
[profile.dev.package.tantivy]
opt-level = 3

[profile.release]
opt-level = "s"
codegen-units = 1
lto = "fat"
strip = true

[dependencies]
zip = { version = "0.6", default-features = false, features = ["deflate"] }
base64 = "0.13"
regex = "1.5"
rouille = { version = "3.5", default-features = false }
rand = "0.8"
chardet = "0.2"
htmlescape = "0.3"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
ctrlc = "3.2"
deepsize = "0.2"
tantivy = { version = "0.17", features = ["mmap"] }
quick-xml = { version = "0.22", features = ["encoding"] }
image = { version = "0.24", default-features = false, features = ["jpeg","png","gif","bmp"] }
encoding = { version = "0.2", default-features = false }
clap = { version = "3.1", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }
atom_syndication = "0.11"
chrono = "0.4"
percent-encoding = "2.1"
rayon = "1.5"
crossbeam-channel = "0.5"
crossbeam-utils = "0.8"
systemstat = "0.1"
bytesize = "1.1"