[package]
name = "porcula"
version = "0.1.0"
authors = ["alexey.s.v.br@gmail.com"]
edition = "2018"

[dependencies]
zip = "0.5.4"
base64 = "0.11.0"
regex = "1.3.4"
rouille = "3.0.0"
rand = "0.7.3"
chardet = "0.2.4"
htmlescape = "0.3.1"
serde = "1.0.104"
serde_json = "1.0.48"

[dependencies.tantivy]
version = "0.12.0"
features = ["mmap"]

[dependencies.quick-xml]
version = "0.17.2"
features = ["encoding"]

[dependencies.image]
version = "0.23.0"
default-features = false
features = ["jpeg","png","gif","bmp"]

[dependencies.encoding]
version = "0.2.33"
default-features = false

[dependencies.clap]
version = "2.33.0"
default-features = false
